### PR TITLE
Add method to add a book to a user's shelves

### PR DESCRIPTION
**Pull request by ryangreenberg**
This is the first non-GET OAuth request in this gem so I had to refactor the methods in request.rb slightly. Let me know what you think.

### CODE REVIEW

**Comment by ryangreenberg** [comment]
I looked at this more closely and I'm unsure whether the object that the Ruby API returns in this PR isn't right. Currently it returns all the shelves that the book is on. Adding a book to a shelf creates a review for that book if it didn't exist before, and the review itself has the list of shelves. One alternative would be to return that review.

**Comment by sosedoff** [comment]
@ryangreenberg what does the API doc say about it ? i haven't used goodreads for a while so i don't know much about these endpoints anymore. In any case - i'm happy to merge this once it's ready.

**Comment by ryangreenberg** [comment]
@sosedoff The docs for [shelves.add_to_shelf](https://www.goodreads.com/api/index#shelves.add_to_shelf) are pretty terse. I see that the top-level of the response object is `<my_review>`, so instead of doing anything fancy I'll switch to use that.

**Example:**

```
<GoodreadsResponse>
  <Request>
    <authentication>true</authentication>
    <key><![CDATA[SECRET_KEY]]></key>
    <method><![CDATA[shelf_add_to_shelf]]></method>
  </Request>
  <my_review>
    <id>2416981504</id>
    <book_id>77084</book_id>
    <rating>0</rating>
    <updated_at>Thu Jun 07 19:58:53 -0700 2018</updated_at>

    <shelves>
        <shelf name="read" exclusive="true" id="269274694" review_shelf_id= ""/>
    </shelves>

    <body></body>
    <body_raw></body_raw>
    <spoiler_flag>false</spoiler_flag>
    <started_at></started_at>
    <read_at></read_at>
    <date_added>Thu Jun 07 19:58:19 -0700 2018</date_added>
  </my_review>
</GoodreadsResponse>
```

**Comment by sosedoff** [comment]
@ryangreenberg is this PR considered to be done?

**Comment by ryangreenberg** [comment]
@sosedoff Yes! Apologies for not saying anything more explicit here. I decided that since the API returns a `<my_review>` it was best to return that object. I didn't appreciate at the time that many operations with the Goodreads API return Review objects where you might not expect them.

Let me know if there are any other changes you'd like to see.

**Pull request merged**
