### PR TITLE
Add a get all user shelves method

### PR DESCRIPTION
**Pull request by seankwon**
- Add get all shelves method of client
- Bump version of active_support to 4.2.5 in order to pass travis ci tests.

### CODE REVIEW

**Comment by sosedoff** [comment]
Do not include VERSION bump in the PR. I change the version when release is ready to be pushed to rubygems.

Also, you are bumping up AS requirement, that means that gem will be broken for anyone that's using older version of AS.

**Comment by seankwon** [comment]
Reverted the number back to its previous version.

Unsure what to do about active support then, as the tests install AS 5.0.0 which break the tests because of it's dependency on json 2

any suggestions? As additions will seem to fail the tests, unless i'm missing something?

**Comment by seankwon** [comment]
I think keeping AS and Json to certain versions will be good, unless this is prone to break a few things?

**Comment by sosedoff** [comment]
Sorry i didnt have time to check out your changes. Are those still relevant? (I see you closed the PR)

**Comment by seankwon** [comment]
The changes seem good, but i was starting to have really bad dependency issues when I was using my version of the gem in a rails 5 application. It might be difficult to make code updates until there's a way to solve these dependency issues, specifically with AS and json. Closing this pull request until i can find a good solution

**Comment by sosedoff** [comment]
I dont think we can depend on older AR stuff forever. If it makes more sense, we can release a version with your changes while keeping the same dependencies and then a another version with breaking changes so that you can use it with AR 5. Just thoughts, im sure it'll be pain to maintain :)

**Comment by seankwon** [comment]
I'm just confused on why AS >= 3.0 is not working for older versions of ruby; the versions on travis are defaulting to use incompatible versions of AS. I tried using the gem with ruby 1.9.3 on my local and it worked perfectly fine. I'm gonna research this a bit more. Until then, this will remain closed.

**Pull request closed without merging**
